2022-05-05 13:49:04,577 - INFO -   File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\trixi\experiment\experiment.py", line 89, in run
    self.train(epoch=self._epoch_idx)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\experiment_template.py", line 155, in train
    y_hat_los, y_hat_mort = self.model(padded, diagnoses, flat)

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\tpc_model2.py", line 721, in forward
    return self.forward_tpc(X=X, diagnoses=diagnoses, flat=flat, time_before_pred=time_before_pred)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\tpc_model2.py", line 766, in forward_tpc
    **kwargs)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\tpc_model2.py", line 464, in temp_pointwise
    X_temp.view(B, point_skip.shape[1], temp_kernels, T)),  # B * (F + Zt) * temp_kernels * T

2022-05-05 13:49:04,578 - INFO - RuntimeError("shape '[64, 174, 12, 335]' is invalid for input of size 22383360")
